package com.stock.harness.tool.validation;

public enum HarnessToolResultValidationReasonCode {
    TOOL_RESULT_VALID,
    RESULT_TYPE_MISMATCH,
    OUTPUT_MISSING,
    OUTPUT_TYPE_MISMATCH,
    OUTPUT_PAYLOAD_MISSING,
    OUTPUT_SYMBOL_MISMATCH,
    OUTPUT_PRICE_INVALID,
    OUTPUT_OBSERVED_AT_MISSING,
    OUTPUT_CURRENT_PRICE_STALE
}
