package com.stock.harness;

public enum HarnessStepType {
    LOAD_PORTFOLIO,
    LOAD_MARKET,
    AUTHORIZE_TOOL_REQUEST,
    CHECK_TOOL_CALL_LIMIT,
    RUN_INVESTMENT_AGENT,
    EXECUTE_TOOL_REQUEST,
    VALIDATE_DECISION,
    EXECUTE_TRADE,
    LOAD_FINAL_PORTFOLIO,
    CHECK_STEP_LIMIT,
    RUN_FAILED
}
