package com.stock.market.stock.master.matching.kisbasicinfo.support;

import com.fasterxml.jackson.databind.node.ObjectNode;
import com.stock.market.stock.basicinfo.provider.kis.parsing.KisStockBasicInfoParser;
import com.stock.market.stock.basicinfo.provider.kis.parsing.result.KisStockBasicInfoParseResult;
import com.stock.market.stock.basicinfo.provider.kis.parsing.support.KisStockBasicInfoParsingFixture;
import com.stock.market.stock.master.collection.result.StockMasterCollectionResult;
import com.stock.market.stock.master.parsing.result.StockMasterBatchParseResult;
import com.stock.market.stock.master.provider.kis.KisStockMasterMarket;
import com.stock.market.stock.master.provider.kis.parsing.KisStockMasterParser;
import com.stock.market.stock.master.provider.kis.parsing.result.KisStockMasterParseResult;
import com.stock.market.stock.master.provider.kis.parsing.support.KisStockMasterParsingFixture;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

import static com.stock.market.stock.master.provider.kis.KisStockMasterMarket.KOSDAQ;
import static com.stock.market.stock.master.provider.kis.KisStockMasterMarket.KOSPI;

public final class KisStockBasicInfoMatchingFixture {
    private KisStockBasicInfoMatchingFixture() {
    }

    public static StockMasterBatchParseResult batch() {
        byte[] flagged = KisStockMasterParsingFixture.row(KOSPI);
        for (int offset : new int[]{90, 121, 122, 123}) {
            KisStockMasterParsingFixture.put(flagged, offset, "Y");
        }
        return batch(KisStockMasterParsingFixture.content(flagged,
                        KisStockMasterParsingFixture.row(KOSPI, "111111", "KR7111111111", "OTHER STOCK")),
                KisStockMasterParsingFixture.content(
                        KisStockMasterParsingFixture.row(KOSDAQ, "0004Y0", "KR70004Y0000", "ALPHA STOCK"),
                        KisStockMasterParsingFixture.row(KOSDAQ, "000250", "KR7000250001", "KOSDAQ STOCK")));
    }

    public static StockMasterBatchParseResult batch(byte[] kospiBytes, byte[] kosdaqBytes) {
        var parser = new KisStockMasterParser();
        var kospi = parser.parse(KOSPI, kospiBytes);
        var kosdaq = parser.parse(KOSDAQ, kosdaqBytes);
        var at = Instant.parse("2026-10-06T00:00:00Z");
        // Synthetic collection metadata retains the hashes generated by the real parsers.
        var collection = new StockMasterCollectionResult(1, UUID.fromString("00000000-0000-0000-0000-000000000001"),
                "CURRENT_OBSERVATION", at, at,
                List.of(observation(kospi, kospiBytes.length, at), observation(kosdaq, kosdaqBytes.length, at)));
        return new StockMasterBatchParseResult(collection, List.of(kospi, kosdaq));
    }

    public static ObjectNode fields(String symbol, String standardCode, String market) {
        return KisStockBasicInfoParsingFixture.output().put("pdno", "00000A" + symbol)
                .put("std_pdno", standardCode).put("mket_id_cd", market);
    }

    public static KisStockBasicInfoParseResult api(String symbol, String standardCode, String market) {
        return api(fields(symbol, standardCode, market));
    }

    public static KisStockBasicInfoParseResult api(ObjectNode fields) {
        return new KisStockBasicInfoParser().parse(KisStockBasicInfoParsingFixture.content(fields));
    }

    private static StockMasterCollectionResult.FileObservation observation(
            KisStockMasterParseResult parsed, int bytes, Instant at
    ) {
        KisStockMasterMarket market = parsed.market();
        return new StockMasterCollectionResult.FileObservation(market, market.sourceUri(), at, at,
                market.name() + "/" + market.fileName() + ".zip", 1, "f".repeat(64),
                market.name() + "/" + market.fileName(), bytes, parsed.inputSha256());
    }
}
