package com.stock.trade;

public enum TradeReasonCode {
    EXECUTION_COMPLETED,
    ORDER_SUBMITTED,
    ACTIVE_BROKER_ORDER_EXISTS,
    BROKER_ORDER_REJECTED,
    ORDER_EXECUTION_DISABLED,
    RISK_DENIED,
    HOLD_NO_ORDER,
    UNSUPPORTED_ACTION
}
