package com.stock.risk;

public enum RiskReasonCode {
    HOLD_NO_ORDER_REQUIRED,
    SYMBOL_REQUIRED,
    QUANTITY_REQUIRED,
    EXPECTED_PRICE_REQUIRED,
    INSUFFICIENT_CASH,
    MAX_ORDER_RATIO_EXCEEDED,
    MAX_POSITION_RATIO_EXCEEDED,
    UNSUPPORTED_ACTION
}
