package com.stock.risk;

public enum RiskReasonCode {
    HOLD_NO_ORDER_REQUIRED,
    RISK_APPROVED,
    SYMBOL_REQUIRED,
    QUANTITY_REQUIRED,
    EXPECTED_PRICE_REQUIRED,
    INSUFFICIENT_CASH,
    MAX_ORDER_RATIO_EXCEEDED,
    MAX_POSITION_RATIO_EXCEEDED,
    POSITION_NOT_FOUND,
    SELL_QUANTITY_EXCEEDS_POSITION,
    UNSUPPORTED_ACTION
}
