package com.stock.harness.tool;

public enum HarnessToolExecutionReasonCode {
    TOOL_EXECUTED,
    TOOL_EXECUTION_FAILED,
    TOOL_NOT_SUPPORTED,
    TOOL_AUTHORIZATION_DENIED,
    DUPLICATE_TOOL_REQUEST,
    PROVIDER_CALL_LIMIT_EXCEEDED,
    PROVIDER_TEMPORARY_FAILURE,
    PROVIDER_PERMANENT_FAILURE
}
